apiVersion: apps/v1
kind: Deployment
metadata:
  name: firehose-deployment
  labels:
    app: firehose
spec:
  selector:
    matchLabels:
      app: firehose
  template:
    metadata:
      labels:
        app: firehose
      annotations:
        prometheus.io/scrape: "true"       # Enable scraping for this pod
        prometheus.io/path: "/metrics"     # Path to scrape metrics from (default is /metrics)
        prometheus.io/port: "80"
    containers:
      - name: firehose
        image: alexkennedy840/firehose:latest
        ports:
          - containerPort: 80
        env:
          REQUEST_ENDPOINT: "http://api.solventdj.com/api/health"
          REQUEST_FREQUENCY: 1
