apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-shell-2
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:latest
      command: ["sleep", "infinity"]
      tty: true
      stdin: true