apiVersion: v1
kind: Namespace
metadata:
  name: blocky
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky-deployment
  labels:
    app: blocky
spec:
  replicas: 7  # Number of desired pods
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      # Configure a topology spread constraint
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: blocky
      containers:
        - name: blocky
          image: alexkennedy840/blocky:latest
          ports:
            - containerPort: 8080
          env:
            - name: INFURA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: infura-api-key
                  key: api_key
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: blocky-service
  labels:
    app: blocky
spec:
  selector:
    app: blocky
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
# TODO: could enable SSL

