controller:
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
dex:
  resources:
    limits:
      cpu: "10m"
      memory: "32Mi"
redis:
  resources:
    limits:
      cpu: "10m"
      memory: "32Mi"
repoServer:
  resources:
    limits:
      cpu: "1000m"
      memory: "512Mi"
server:
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: a84eda6df1be84aa3b7899cec1a71161-528283014.us-east-1.elb.amazonaws.com

configs:
  params:
    server.insecure: true
